### ISSUE TITLE
빌드 에러 질문드립니다.

### ISSUE THREAD

**Issue by hyeonhh** [movieAppreciate/filmo_AOS#24]
## 빌드 에러 질문
상현님 올려주신 코드를 받아서 실행시켜주려고 하니 아래와 같은 에러로 빌드가 되지 않는 문제가 있습니다!
확인 한번만 부탁드립니다 😄 
### 에러 발생 코드
![image](https://github.com/movieAppreciate/filmo_AOS/assets/96102917/1adeb291-94bb-4183-b894-05a6d6bb71f6)

### 에러 내용
![image](https://github.com/movieAppreciate/filmo_AOS/assets/96102917/8026eb8e-66ec-4ae7-9349-fff04c4b3d8d)
-  17번째 코드 : Ktlint rule with id 'ktlint:standard:backing-property-naming' is unknown or not loaded (cannot be auto-corrected)
- 18번째 코드 : Backing property name is only allowed when a matching public property or function exists (cannot be auto-corrected)

**Comment by Hoyuo** [comment]
#25
